### ISSUE TITLE
Wrong indent for annotation in otherwise empty model

### ISSUE THREAD

**Issue by m-kessler** [ErykMroczek/mofmt#38]
Similar to #31, annotation indent is too high if the model only contains an annotation (like for documentation classes or extendable icons).

This code for example:
```
partial model Example
  "Icon for runnable examples"
  annotation (Icon(graphics = {Ellipse(extent = {{-100, -100}, {100, 100}})}));
end Example;
```

Produces:
```
partial model Example
  "Icon for runnable examples"
    annotation (Icon(graphics = {Ellipse(extent = {{-100, -100}, {100, 100}})}));

end Example;
```

The error does not occur when the model comment is deleted or if variable declarations are added.

Tested with mofmt 0.5.0 and 0.4.2.

**Comment by ErykMroczek** [comment]
Eh, the issue is that Modelica syntax in the *composition* context is quite liberal:

```none
[ external [ language-specification ] [ external-function-call ] [ annotation-clause ] ";" ]

[ annotation-clause ";" ] 
```

Problem is to differentiate between first and second annotation, because it is syntactically valid to have `external` keyword followed by the `annotation-clause`, and nothing more. Would it annotation refer to the external element, or to the whole class?

It can be said that from the semantical standpoint it doesn't make sense to have an annotation to the external function without the `external-function-call` (prototype), but the thing is it can still happen., and needs to handled somehow. I am not sure at this moment, what heuristic I should apply here, to guard against such edge cases.

I will fix this specific issue though.

**Comment by m-kessler** [comment]
> Problem is to differentiate between first and second annotation, because it is syntactically valid to have `external` keyword followed by the `annotation-clause`, and nothing more. Would it annotation refer to the external element, or to the whole class?

I don't understand. You mean something like this?
```
function f
  external annotation(...);
end f;
```
Here the annotation is clearly part of the external keyword. The class annotation would be
```
function f
  external;
  annotation(...);
end f;
```

**Comment by ErykMroczek** [comment]
You are right, of course.
Sorry, looks like I was tired when I wrote that, and missed the semicolon.

**Comment by ErykMroczek** [comment]
BTW, as we mentioned the `external` part - currently `mofmt` formats the external calls like this:

```modelica
external "C"

  foo = bar(x, y, z)
    annotation (...);
```

I decided that it is more in line with how `equation` section etc. are formatted, and the code is more consistent visually. But previously it was something like:

```modelica
external "C" foo = bar(x, y, z)
  annotation (...);
```

Any issue with the new approach?

**Comment by ErykMroczek** [comment]
Turning off Dymola's autoformatting would be the most welcome feature.

I agree that it is not fully equivalent to `equation` syntax-wise, but still when go through files I "scan" them in a similar fashion.

Let's leave it for now. I will think about it.
