### ISSUE TITLE
Unnecessary whitespace for selective model extension

### ISSUE THREAD

**Issue by m-kessler** [ErykMroczek/mofmt#46]
The selective model extension, which mofmt supports since #6, is not formatted correct.

This code:
```
model NewPlant
  extends System(
    break controller,
    break reference);
end NewPlant;
```

Is formatted as:
```
model NewPlant

  extends System(
    break controller ,
    break reference );

end NewPlant;
```

Note the extra white spaces at the end of each break statement.

**Comment by ErykMroczek** [comment]
Fixed in [d3c7293](https://github.com/ErykMroczek/mofmt/pull/47/commits/d3c729387def5c26978228c5ea06fea3d445e061), so you can use this commit in `pre-commit`. For manual usage, use command `cargo install --git`.

It will be included in `0.6.0`, but I will wait with the release until I implement HTML formatting.
